server:
  port: 8081

spring:
  application:
    name: auth-service

  # Configuracion de Jackson (JSON)
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

# Configuracion de Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Configuracion de Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Configuracion de JWT
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970


  expiration: 3600000  # 1 hora en milisegundos (1000 * 60 * 60)
  refresh-expiration: 604800000  # 7 días en milisegundos (1000 * 60 * 60 * 24 * 7)

# Configuracion de Feign (para comunicarse con User Service)
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

# Logging
logging:
  level:
    com.ecommerce.auth: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"