version: '3.8'

services:
  postgres-user:
    image: postgres:15-alpine
    container_name: postgres-user-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce123
    ports:
      - "5432:5432"
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

volumes:
  postgres-user-data:

networks:
  ecommerce-network:
    driver: bridge